### ISSUE TITLE
Load T5 TextEncoder ELLA - Required input is missing: name

### ISSUE THREAD

**Issue by Duemellon** [TencentQQGYLab/ComfyUI-ELLA#13]
Downloaded JSON files have this prefix: 
models--google--flan-t5-xl--text_encoder_... json

example pic has this:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/b7fc945b-43d1-4515-82a5-92ae21f51a61)

model structure in installation info README.MD has this, which suggests we trim the prefix down:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/cc21130b-bbb4-45d6-a76b-f5f9cdc1e3c2)

I have them installed here, as this:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/8e9269b1-4a81-4713-8114-eca8773f6358)

And I get this message from ComfyUI:
_Failed to validate prompt for output 12:
* T5TextEncoderLoader #ELLA 13:
  - Required input is missing: name
* T5TextEncode #ELLA 7:
  - Required input is missing: text_encoder
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
got prompt
Failed to validate prompt for output 12:
* T5TextEncoderLoader #ELLA 13:
  - Required input is missing: name
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}_

When I change the file names to remove the prefixes to be this:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/3db3f273-6556-4174-8f68-7c6d1455e53d)

close my browser & restart ComfyUI
I get this:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/0f423a42-54e1-47d1-9b36-a22684d7ab16)
And when I click the arrow to select it becomes this:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/1226809e-2b7f-491d-af8f-206d4a9cad81)

And this when I try to run:
Failed to validate prompt for output 12:
_* T5TextEncoderLoader #ELLA 13:
  - Required input is missing: name
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}_

**Comment by JettHu** [comment]
May I ask what method you used for downloaded and which t5 model link?

**Comment by Duemellon** [comment]
I used this link:
https://huggingface.co/QQGYLab/ELLA/tree/main/models--google--flan-t5-xl--text_encoder

I clicked these arrows individually:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/63836c55-7104-4556-b968-977517528b90)

**Comment by JettHu** [comment]
I recommend git clone as it's easier.

<img width="1613" alt="image" src="https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/3469a33f-a43f-435a-8879-d9ae4b9f4d76">

Or use [hugginface_hub client](https://huggingface.co/docs/hub/models-downloading#using-the-hugging-face-client-library).

**Comment by Duemellon** [comment]
I didn't know such a thing existed! 
It's under the stacked tri-dots. 

OK, I'll do that.

**Comment by Duemellon** [comment]
Finally. After the Git Clone I then moved the files to the proper directories & the Blank in the Node filled in. 

Thanks.

**Comment by Suka4GitHub** [comment]
- Value not in list: name: 'models--google--flan-t5-xl--text_encoder' not in []

as per above...... no luck!
