### ISSUE TITLE
Output image quality is unstable

### ISSUE THREAD

**Issue by PetitPrinceb612** [TencentQQGYLab/ComfyUI-ELLA#14]
Hi, thank you for developing the comfyui-ELLA. I got it for the first time and compared it with the SD15 general process. I don’t know if it is a problem with my settings. I tested a lot of prompts and found that the Ella img rendering effect is very unstable and not good. And No matter how you adjust it, it is difficult to improve the img quality. Do you have better preset parameters?
 
workflow is here
![workflow](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/46679983/99b3d6fc-dc6b-48a3-8c7e-1ad5e77c248d)

**Comment by user-vm** [comment]
I'm getting similar issues, it seems to not like batch sizes different from 1. With batch size 4, I get one clear image that doesn't fully match the prompt, two low quality ones, and one borken and noisy image,  The simple diffusers wrapper works properly for batch size 4. Same settings I think:
[workflow_ella.json](https://github.com/TencentQQGYLab/ComfyUI-ELLA/files/15050139/workflow_ella.json)
[workflow_ella_diffusers.json](https://github.com/TencentQQGYLab/ComfyUI-ELLA/files/15050140/workflow_ella_diffusers.json)

**Comment by JettHu** [comment]
> I'm getting similar issues, it seems to not like batch sizes different from 1. With batch size 4, I get one clear image that doesn't fully match the prompt, two low quality ones, and one broken and noisy image. The simple diffusers wrapper version works properly for batch size 4 - https://github.com/kijai/ComfyUI-ELLA-wrapper . Same settings I think: [workflow_ella.json](https://github.com/TencentQQGYLab/ComfyUI-ELLA/files/15050139/workflow_ella.json) [workflow_ella_diffusers.json](https://github.com/TencentQQGYLab/ComfyUI-ELLA/files/15050140/workflow_ella_diffusers.json)

Thanks for raising the possible issue. I will look at the multi-batch situation.

**Comment by quixot1c** [comment]
FYI, batch sizes of 3, 5, 6 and 7 plain give errors, while batch size 2, 4 and 8 work.

8 gives some funny results:
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/78642781/2ca695cc-c0d3-4e85-b1f3-0758046b6b67)

**Comment by JettHu** [comment]
Fixed! it will be released as soon as possible after testing

<img width="1439" alt="image" src="https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/af544f4c-e934-4017-be18-10bd86a6aa06">
