### ISSUE TITLE
Concat conditionings

### ISSUE THREAD

**Issue by m0rtus59** [TencentQQGYLab/ComfyUI-ELLA#16]
I get this error when trying to concat ELLA and CLIP conditionings together. I'm trying to do this to inject trigger words and/or embeddings. In [ExponentialML](https://github.com/ExponentialML)'s implementation this works though. Is there a way to work around this?

```Error occurred when executing ConditioningConcat:

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)

File "E:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\ComfyUI\ComfyUI\nodes.py", line 133, in concat
tw = torch.cat((t1, cond_from),1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Comment by Duemellon** [comment]
I've used Conditioning Combine, not Concat & that works w/o error.

I was using it for Lora keywords (take the model directly from checkpoint to Lora, then Lora's model output to Ella) and combine an empty conditioning from the Lora w/Ella right before KSamplers

**Comment by JettHu** [comment]
Condition from `ELLA Apply` node is just for controlnet and inpainting, is not actually into KSampler, It will be replaced by EllaUnetProxy so far. I will try to solve this problem.

**Comment by m0rtus59** [comment]
Okay, I feel a bit stupid. I was using the CLIP Text Encode++ node from [smZNodes](https://github.com/shiimizu/ComfyUI_smZNodes) and that's why it worked. Although now it seems that concatenating conditions doesn't seem to do anything, as well as multi-area conditioning not working properly. Looking forward to future updates 🙂.

**Comment by JettHu** [comment]
This is going to be included in this week's work.

**Comment by JettHu** [comment]
released.

**Comment by m0rtus59** [comment]
Thanks. Works fine now!

**Comment by m0rtus59** [comment]
sa
