### ISSUE TITLE
Load T5 Text Encoder dropdown is empty

### ISSUE THREAD

**Issue by eliganim** [TencentQQGYLab/ComfyUI-ELLA#18]
I followed the instructions in the readme file and put all files in the correct location:
![Screenshot 2024-04-21 at 15 36 46](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/850349/0cb29c6b-0642-4f81-87fc-a80ee1d69837)

However, when I open the example workflow I get this:
![Screenshot 2024-04-21 at 15 37 27](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/850349/0c66369e-5e65-4e12-8d49-16a4b6c2360a)

Looks like it can't find the necessary file. What am I doing wrong?

**Comment by eliganim** [comment]
Nevermind. The filenames were wrong 🤦‍♂️
They shouldn't have the prefix `models--google--flan-t5-xl--text_encoder`

**Comment by qingzhenbiaojie** [comment]
@eliganim I have not been able to find a solution, directly I see this reply from you, change the name and it will run, can not understand why this file name still needs to be changed manually to be recognized correctly when downloading, many people do not know,by the way ,thx u bro!
