### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half' when executing T5TextEncode #ELLA

### ISSUE THREAD

**Issue by Akira13641** [TencentQQGYLab/ComfyUI-ELLA#19]
I am running the latest ComfyUI. My GPU is an Nvidia GTX 1660 Ti (desktop version, 6GB VRAM, Turing architecture).
I launch ComfyUI with the `run_nvidia_gpu.bat` file.

**Comment by JettHu** [comment]
Have you tried `--fp32-text-enc` mentioned in #12

**Comment by Akira13641** [comment]
That fixed it! Thanks a lot.
