### ISSUE TITLE
批次生图时报错或者没有正常工作？

### ISSUE THREAD

**Issue by Jacob-HYG** [TencentQQGYLab/ComfyUI-ELLA#21]
当我增加批次到2时，只有第一张是正常的，此外我还发现当批次为单数批次时则报错，双数则不会，随着批次增加，生成的图片越糟糕

![Snipaste_2024-04-22_13-26-39](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/47966262/3d4ec7fc-620e-48b5-b0d1-fb2c40b2720a)
![Snipaste_2024-04-22_13-28-33](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/47966262/c663331e-2ac3-44a4-aa76-6d53e893e585)
![Snipaste_2024-04-22_13-31-54](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/47966262/a1dc7807-f61e-49cf-a125-0106c44bffda)

**Comment by JettHu** [comment]
duplicate with #14
