### ISSUE TITLE
Smaller T5_model

### ISSUE THREAD

**Issue by seanphan** [TencentQQGYLab/ComfyUI-ELLA#3]
Incredible work, thank you so much.

Instead of the original T5 model I find this also working https://huggingface.co/ybelkada/flan-t5-xl-sharded-bf16/tree/main

6GB vs 10GB.

Maybe you can clone a repo of T5 that has minimum requirements and can auto install with pip?

**Comment by kijai** [comment]
It only needs the encoder, so it can be halved from that: https://huggingface.co/Kijai/flan-t5-xl-encoder-only-bf16/tree/main

**Comment by wangfeng35** [comment]
> It only needs the encoder, so it can be halved from that: https://huggingface.co/Kijai/flan-t5-xl-encoder-only-bf16/tree/main

You rock!!! It saves a lot of space!

**Comment by kijai** [comment]
They seem to have official one too here:
https://huggingface.co/QQGYLab/ELLA/tree/main/models--google--flan-t5-xl--text_encoder

**Comment by seanphan** [comment]
@kijai awesome !!

**Comment by JettHu** [comment]
> They seem to have official one too here:
> https://huggingface.co/QQGYLab/ELLA/tree/main/models--google--flan-t5-xl--text_encoder

Yeah, the encoder only t5-xl was just pushed on hf hub. 
Try this one. @seanphan

**Comment by seanphan** [comment]
Thank you !! @JettHu

**Comment by JettHu** [comment]
close it.
