### ISSUE TITLE
AYS + Ella = anyone else getting superdark image generations?

### ISSUE THREAD

**Issue by Duemellon** [TencentQQGYLab/ComfyUI-ELLA#39]
When I combine the the images came out dark, like barely discernible using EpicRealism 1.5 & some other models. Is this a thing for other people too?

**Comment by Duemellon** [comment]
I think it's the default step count for AYS that was 10. Changed it 20 & it makes it better.

**Comment by Duemellon** [comment]
still darker than usual even with more steps.

**Comment by JettHu** [comment]
I think AYS `steps` and `denoise` should be the same as `Set ELLA Timesteps` node. Do you mind share your workflow?

**Comment by Duemellon** [comment]
15 step, euler
![ComfyUI_04940_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/8ecb1f6f-a6bb-4734-86ce-5e2ca25c127b)

20 step euler
![ComfyUI_04949_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/da282aa4-0950-410c-8632-e95fa3941298)

30 step euler
![ComfyUI_04955_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/eefd2632-beba-4d25-a1b0-5ea1828e801b)

20 step dpmpp
![ComfyUI_04956_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/35391f08-56a3-4d57-a434-13b6e9388a66)

30 step dpmpp
![ComfyUI_04961_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/3d411113-e13a-43dd-8b7d-611fd14a9ac2)

20 step euler 
![ComfyUI_04971_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/1ec27195-4b01-44db-b9a5-8d35b231b8d0)

30 step dpmpp 
![ComfyUI_04967_](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/113479041/e330876a-4b2b-48a1-9e37-3230176b8c3b)

Maybe it's the model? I tried other models & they trend this way too. No one else seems to be having this complaint so it's probably just something I'm doing.

[ELLA-AYS.json](https://github.com/TencentQQGYLab/ComfyUI-ELLA/files/15221555/ELLA-AYS.json)

**Comment by JettHu** [comment]
I noticed that add_noise is turned off in your workflow. 

<img width="601" alt="image" src="https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/1afe7cb7-a9b2-44d3-bca5-da4933fa6311">

You can try turning it on. 

| steps | add_noise on | add_noise off |
| :--- | :---: | :---: |
| 20 | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/16c28d6f-9670-41bb-a366-6b5d3e6b7d19) | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/09da7b96-dcc1-4391-8083-64d790ab45e0) |
| 10 | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/2edd5582-f21a-4961-90c2-cd17ff31317b)| ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/c0b8fef1-f2ae-4480-bc62-506692a97e5b)|

However, I did find that the quality of the generated images will be higher when the steps are larger.

**Comment by JettHu** [comment]
> I think AYS `steps` and `denoise` should be the same as `Set ELLA Timesteps` node. Do you mind share your workflow?

Sorry, what I said before is wrong. Once the `sigmas` is given to `Set ELLA Timesteps` node, it's other  parameters (`scheduler`, `steps`, and `denoise`) will not take effect.

**Comment by JettHu** [comment]
In addition, it may be necessary to lower the cfg

The results in the paper used DPM-Solver++(2M) with 10 steps, so I used the same parameters to generate more images:

> KSamplerSelect sampler_name: dpmpp_2m; AlignYourStepsScheduler model_type: SD1, steps: 10, denoise: 1.0
> 
> all result with `same noise_seed`

| cfg | 3 | 4 | 5 | 6 | 7 | 8 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/3daecf2b-1bc1-47a8-99ec-a5e4329c67f3) |![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/8e586091-9377-4f75-811d-96ba1be04505)| ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/078129b2-1f06-448a-a9ac-88a5c1c36c20) | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/04e7fa2c-00fd-4dc0-8564-44c75cce4f7d) | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/3caa8cd5-32a5-484c-b256-174cbd1b9aff) | ![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/35261585/283112e7-975a-4698-8021-f1039fe70362) |

**Comment by Duemellon** [comment]
add noise, CFG, & step count helped
