### ISSUE TITLE
Question: Using Embeddings in T5 Text Encode Node

### ISSUE THREAD

**Issue by Architech-Eddie** [TencentQQGYLab/ComfyUI-ELLA#47]
Hello,

Thank you for the great work on this project!

I have a question regarding the usage of embeddings in the T5 Text Encode node. Is it appropriate to use embeddings in this context, given that they are originally used under the CLIP Text Encode node?

Thank you for your assistance!

**Comment by shiccup** [comment]
I also am having a question about using IPadapter with this node I want to use the IP adapter embedding in combination with Ella but the nodes are values are not compatible I have been attempting to fix this myself but it seems Ella does not play well when it comes to trying to import its packages into other nodes. I feel like this should be simple, but I am not experienced enough to fix it myself. The idea behind this is it seems alot easier to use ella for positive prompts and I would like to use IP adapter as its just a blanket image embedding tool it could use the previous frame generated to improve the quality (what the image looks like) of the current frame while ella is used for the context (what the image is of) and I think if those 2 were brought together it would be amazing.
