### ISSUE TITLE
On a mac: Error occurred when executing T5TextEncoderLoader

### ISSUE THREAD

**Issue by andupotorac** [TencentQQGYLab/ComfyUI-ELLA#59]
Error occurred when executing T5TextEncoderLoader #ELLA:

Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /Users/andu/ComfyUI/models/ella_encoder/models--google--flan-t5-xl--text_encoder.

File "/Users/andu/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/andu/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/andu/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/andu/ComfyUI/custom_nodes/ComfyUI-ELLA/ella.py", line 381, in load
t5_encoder = T5TextEmbedder(t5_file, max_length=max_length or None, dtype=dtype) # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/andu/ComfyUI/custom_nodes/ComfyUI-ELLA/model.py", line 127, in __init__
self.model = T5EncoderModel.from_pretrained(pretrained_path).to(self.dtype) # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/andu/miniforge3/envs/comfyenv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3482, in from_pretrained
raise EnvironmentError(

**Comment by andupotorac** [comment]
Do I have to add new files to that folder? And if yes, are there any instructions because I followed the steps in the readme and added the T5 model and assets there as per the folder structure given.

**Comment by JettHu** [comment]
You can refer to the readme.
```bash
ComfyUI/models/ella/
└── ella-sd1.5-tsc-t5xl.safetensors

ComfyUI/models/ella_encoder/
└── models--google--flan-t5-xl--text_encoder
    ├── config.json
    ├── model.safetensors
    ├── special_tokens_map.json
    ├── spiece.model
    ├── tokenizer_config.json
    └── tokenizer.json
```

And, I'm going to add the function of automatically downloading models.

**Comment by andupotorac** [comment]
> You can refer to the readme.
> 
> ```shell
> ComfyUI/models/ella/
> └── ella-sd1.5-tsc-t5xl.safetensors
> 
> ComfyUI/models/ella_encoder/
> └── models--google--flan-t5-xl--text_encoder
>     ├── config.json
>     ├── model.safetensors
>     ├── special_tokens_map.json
>     ├── spiece.model
>     ├── tokenizer_config.json
>     └── tokenizer.json
> ```
> 
> And, I'm going to add the function of automatically downloading models.

I did, and this is precisely the structure I have. I thought they're supposed to be in models--google--flan-t5-xl--text_encoder folder.

**Comment by andupotorac** [comment]
Never mind my structure was wrong, this is  now ok: 
<img width="932" alt="Screenshot 2024-08-16 at 15 05 03" src="https://github.com/user-attachments/assets/65d39440-8ccb-4d14-af06-a181c61982cd">
