### ISSUE TITLE
节点失败了

### ISSUE THREAD

**Issue by zhaowolf** [TencentQQGYLab/ComfyUI-ELLA#7]
When loading the graph, the following node types were not found:
ELLALoader
T5TextEncoderLoader #ELLA
加载失败的节点会显示为红色

**Comment by huagetai** [comment]
已经提交了修正的PR

**Comment by ErvinA-wx** [comment]
我也是这样。

**Comment by Piscabo** [comment]
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/123719842/24a72257-a6d8-4b64-bc6d-87300c48abd5)
Same problem.

**Comment by ErvinA-wx** [comment]
> 我也是这样。

![Uploading {A655F7DE-877D-4fcc-B7EF-EEAEF69028D2}.png…]()

**Comment by FNSpd** [comment]
Setting paths manually in extra_model_paths.yaml fixed it for me

**Comment by amir84ferdos** [comment]
I used this fix: 
https://github.com/TencentQQGYLab/ComfyUI-ELLA/pull/9/commits/a77a650b7be8887c326a22a4b5466ec50c9562d8

now it is working 
![image](https://github.com/TencentQQGYLab/ComfyUI-ELLA/assets/130132760/f6af21f2-9514-4e30-89a0-e6d89891a316)

**Comment by JettHu** [comment]
fixed by [PR #8](https://github.com/TencentQQGYLab/ComfyUI-ELLA/pull/8), already merged.
